version: '2'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    # logging:
    #   driver: none
  mongo:
    image: mongo:2.6
    command: --smallfiles
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db
    logging:
      driver: none
  redis:
    image: redis:3.0
    ports:
      - "6379:6379"
    logging:
      driver: none
  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./database/elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: none
  admin:
    build:
      context: .
      dockerfile: docker/admin-service/Dockerfile.local
      args:
        # build-time ENV parameters
        RAILS_ENV: development
    depends_on:
      - elasticsearch
      - mysql
      - mongo
      - redis
    entrypoint: ./development.sh
    env_file: ./.env
    ports:
      - "3000:80"
    environment:
      # runtime ENV parameters
      RAILS_ENV: development
      RAILS_COOKIE_TOKEN: 6f1d70d3424620e9007f62d2a8ee3d023b728ae15e57035de9f026e4874ba80d9b8968b1cd3321e58f4fb04aac07f8fee9b7ea543b305240dea6814e6ecec3ca
    volumes:
      - ./:/voc:rw
    tty: true
    stdin_open: true
  public:
    build:
      context: ../gsa_comment_tool_public
      dockerfile: Dockerfile.local
      args:
        # build-time ENV parameters
        RAILS_ENV: development
    depends_on:
      - mysql
      - mongo
      - redis
    entrypoint: ./development.sh
    env_file: ./.env
    ports:
      - "4000:8080"
    environment:
      # runtime ENV parameters
      RAILS_ENV: development
      RAILS_COOKIE_TOKEN: 2dae529320f622ab8a7501f899aab112b000748a6060959d26fdc0146aed1dc2cc7ba52712542cfddfb9064218ce052d754f22150785dd09566ea7201a061f80
    tty: true
    stdin_open: true
  admin_worker:
    build:
      context: .
      dockerfile: docker/admin-worker-service/Dockerfile.local
      args:
        # build-time ENV parameters
        RAILS_ENV: staging
    depends_on:
      - mysql
      - mongo
      - redis
    env_file: ./.env
    entrypoint: ./wait-for-it.sh -t 0 admin:80 -- bundle exec rake resque:work
    environment:
      # runtime ENV parameters
      RAILS_ENV: development
      RAILS_COOKIE_TOKEN: 6f1d70d3424620e9007f62d2a8ee3d023b728ae15e57035de9f026e4874ba80d9b8968b1cd3321e58f4fb04aac07f8fee9b7ea543b305240dea6814e6ecec3ca
    volumes:
      - ./:/voc
  web:
    image: nginx:alpine
    logging:
      driver: none
    depends_on:
      - admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/web/certs:/certs:ro
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
