# Example mailer_settings.yml layouts, showing configuration for
# sendmail or SMTP connections

development:
  raise_delivery_errors: false
  default_url_options:
    host: <%= ENV['MAILER_HOST'] %> # required parameter, determines FROM address
  delivery_method: :file

production:
  raise_delivery_errors: false
  default_url_options:
    host: <%= ENV['MAILER_HOST'] %> # required parameter, determines FROM address
  delivery_method: :smtp
  smtp_settings:
    :address: <%= ENV['SMTP_ADDRESS'] %>
    :port: <%= ENV['SMTP_PORT'] %>
    :domain: <%= ENV['SMTP_DOMAIN'] %>
    :user_name: <%= ENV['SMTP_USER'] %>
    :password: <%= ENV['SMTP_PASS'] %>
    :authentication: <%= ENV['SMTP_AUTH'] %>
