development:
  raise_delivery_errors: false
  default_url_options: { :host: localhost:3000 }
  delivery_method: :test
  smtp_settings: { :address: smtp.mxes.net,
                   :port: 25,
                   :domain: ctacorp.com,
                   :user_name: emailalertbccs_paperworkreduction.gov,
                   :password: icras555alerts,
                   :authentication: :login }
production:
  raise_delivery_errors: false
  default_url_options: {:host => 'comment-app.hhs.gov'}
  delivery_method: :smtp
  smtp_settings: { :address: smtp.mxes.net,
                   :port: 25,
                   :domain: ctacorp.com,
                   :user_name: emailalertbccs_paperworkreduction.gov,
                   :password: icras555alerts,
                   :authentication: :login }
test:
